#################################################################
##### 应用开发环境配置                                        ######
#################################################################
server:
  port: 8080

# 数据库调用日志输出配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  # 配置关系型数据库(Mariadb)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/epub_reading_service?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  # 配置非关系型数据库(Redis)
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

# Sa-token 验证配置
sa-token:
  token-name: satoken
  timeout: -1
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid

# 应用全局配置
appConfig:
  # 配置外部数据存储
  dataStorage:
    dataDirRoot: /Users/heng/workspace/sync-reading-management-api/ProjectData
    uploadedTmpPrefix: /tmps
    bookCoverPrefix: /covers
    bookResPrefix: /books